name: ebsi
description: EBSI wallet compliance
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: 3.3.7

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  crypto: ^3.0.2
  cryptography: ^2.5.0
  dart_bip32_bip44: ^0.2.0
  dart_jsonwebtoken: ^2.7.1
  dart_web3: ^0.0.3
  dio: ^4.0.6
  fast_base58: ^0.2.1
  flutter:
    sdk: flutter
  hex: ^0.2.0
  http_mock_adapter: ^0.3.3
  jose: ^0.3.3
  json_path: ^0.4.2
  pinenacl: ^0.3.3 # tezart from git depends on pinenacl ^0.3.3
  secp256k1: ^0.3.0
  tezart:
    git:
      url: https://github.com/autonomy-system/tezart.git
      ref: bd4b8db6e3a352590a6e556d31df8aef60db3465
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^4.0.0+1
