name: credential_manifest
description: Credential Manifest reading and interpretation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  json_path: ^0.7.2 #latest version creates test issue

dev_dependencies:
  build_runner: ^2.8.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.11.1
  very_good_analysis: ^9.0.0
