name: credential_manifest
description: Credential Manifest reading and interpretation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^4.0.6
  flutter:
    sdk: flutter
  json_annotation: ^4.8.0
  json_path: ^0.4.2

dev_dependencies:
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.0
  very_good_analysis: ^3.1.0