name: credential_manifest
description: Credential Manifest reading and interpretation
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  dio: ^5.3.2
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  json_path: ^0.4.4 #latest version creates test issue

dev_dependencies:
  build_runner: ^2.4.4
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.0
  very_good_analysis: ^5.0.0+1
