import 'package:altme/dashboard/home/home.dart';
import 'package:flutter/material.dart';

part 'credential_subject_type_extension.dart';

enum CredentialSubjectType {
  bloometaPass,
  tezoniaPass,
  tzlandPass,
  troopezPass,
  pigsPass,
  matterlightPass,
  dogamiPass,
  bunnyPass,
  tezotopiaMembership,
  chainbornMembership,
  ageRange,
  nationality,
  gender,
  walletCredential,
  tezosAssociatedWallet,
  ethereumAssociatedWallet,
  fantomAssociatedWallet,
  polygonAssociatedWallet,
  binanceAssociatedWallet,
  tezosPooAddress,
  ethereumPooAddress,
  fantomPooAddress,
  polygonPooAddress,
  binancePooAddress,
  certificateOfEmployment,
  defaultCredential,
  ecole42LearningAchievement,
  emailPass,
  identityPass,
  verifiableIdCard,
  linkedInCard,
  learningAchievement,
  loyaltyCard,
  over18,
  over13,
  passportFootprint,
  phonePass,
  professionalExperienceAssessment,
  professionalSkillAssessment,
  professionalStudentCard,
  residentCard,
  selfIssued,
  studentCard,
  voucher,
  tezVoucher,
  talaoCommunityCard,
  diplomaCard,
  aragoPass,
  aragoEmailPass,
  aragoIdentityCard,
  aragoLearningAchievement,
  aragoOver18,
  pcdsAgentCertificate,
  twitterCard,
}
