name: secure_jwt_signer
description: Sign jwt with keys from TEE/Strongbox or Secure Element
version: 0.1.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  crypto: ^3.0.3
  secp256r1: ^0.1.0-dev.7

dev_dependencies:
  mocktail: ^1.0.3
  test: ^1.19.2
  very_good_analysis: ^5.0.0+1
