name: did_kit
description: DidKit Package
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  didkit:
    path: ../../../didkit/lib/flutter
  dio: 5.6.0
  flutter:
    sdk: flutter
  mocktail: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
