name: did_kit
description: DidKit Package 
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  didkit:
    path: ../../../didkit/lib/flutter
  flutter:
    sdk: flutter
  mocktail: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^4.0.0+1