name: credential_manifest

on: [pull_request, push]

jobs:
  build:
    uses: TalaoDAO/AltMe/.github/workflows/flutter_package.yaml@main
    with:
      flutter_channel: stable
      flutter_version: 3.22.1
      min_coverage: 30
      working_directory: packages/credential_manifest
      dart_sdk: 3.4.1
