name: cryptocurrency_keys

on: [ pull_request, push ]

jobs:
  build:
    uses: TalaoDAO/AltMe/.github/workflows/flutter_package.yaml@main
    with:
      flutter_channel: stable
      flutter_version: 3.19.6
      min_coverage: 95
      working_directory: packages/cryptocurrency_keys
