name: oidc4vc

on: [pull_request, push]

jobs:
  build:
    uses: TalaoDAO/AltMe/.github/workflows/flutter_package.yaml@main
    with:
      flutter_channel: stable
      flutter_version: 3.19.6
      min_coverage: 30
      working_directory: packages/oidc4vc
      dart_sdk: 3.3.4
      build_runner: false
