import 'package:altme/app/app.dart';
import 'package:altme/l10n/l10n.dart';
import 'package:flutter/material.dart';

part 'network_error_extension.dart';

enum NetworkError {
  NETWORK_ERROR_NOT_IMPLEMENTED,
  NETWORK_ERROR_REQUEST_CANCELLED,
  NETWORK_ERROR_INTERNAL_SERVER_ERROR,
  NETWORK_ERROR_SERVICE_UNAVAILABLE,
  NETWORK_ERROR_METHOD_NOT_ALLOWED,
  NETWORK_ERROR_BAD_REQUEST,
  NETWORK_ERROR_UNAUTHORIZED_REQUEST,
  NETWORK_ERROR_UNEXPECTED_ERROR,
  NETWORK_ERROR_REQUEST_TIMEOUT,
  NETWORK_ERROR_NO_INTERNET_CONNECTION,
  NETWORK_ERROR_CONFLICT,
  NETWORK_ERROR_SEND_TIMEOUT,
  NETWORK_ERROR_UNABLE_TO_PROCESS,
  NETWORK_ERROR_NOT_ACCEPTABLE,
  NETWORK_ERROR_GATEWAY_TIMEOUT,
  NETWORK_ERROR_TOO_MANY_REQUESTS,
  NETWORK_ERROR_UNAUTHENTICATED,
  NETWORK_ERROR_NOT_FOUND,
}
